version: "3.0"
services:
  antidote1:
    image: antidotedb/antidote:0.2.0
    ports:
     - "8087:8087"
    environment:
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"
    deploy:
      placement:
        constraints: [node.role == manager]
        
  antidote2:
    image: antidotedb/antidote:0.2.0
    ports:
     - "8088:8087"
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"
    deploy:
      placement:
        constraints: [node.role == manager]
              
  antidote3:
    image: antidotedb/antidote:0.2.0
    ports:
     - "8089:8087"
    environment:
      NODE_NAME: "antidote@antidote3"
      SHORT_NAME: "true"
    deploy:
      placement:
        constraints: [node.role == worker]

  link:
    image: erlang:19-slim
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ready"]
      interval: 3s
      timeout: 1s
      retries: 10
    volumes:
      - .:/code
    command: '/code/connect_dcs.sh'
    deploy:
      placement:
        constraints: [node.role == manager]    
