version: "3.0"
services:
  antidote1:
    image: itoumlilt/antidotedb:v0.2.0-alpine-iptables
    ports:
     - "8087:8087"
    environment:
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"
    deploy:
      placement:
        constraints: [node.hostname == antidote1 ]
        
  antidote2:
    image: itoumlilt/antidotedb:v0.2.0-alpine-iptables
    ports:
     - "8088:8087"
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"
    deploy:
      placement:
        constraints: [node.hostname == antidote2]
              
  antidote3:
    image: itoumlilt/antidotedb:v0.2.0-alpine-iptables
    ports:
     - "8089:8087"
    environment:
      NODE_NAME: "antidote@antidote3"
      SHORT_NAME: "true"
    deploy:
      placement:
        constraints: [node.hostname == antidote3]

  link:
    image: erlang:21-slim
    volumes:
      - .:/code
    command: '/code/connect_dcs.sh'
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure    
